### PR TITLE
Readme edit

### PR DESCRIPTION
**Pull request by Louis-Clelland**
I have fixed the README.md file

### CODE REVIEW

**Comment by john-rob-dev** [comment]
Please change fro to for then we can get this merged.

**Comment by Louis-Clelland** [comment]
ok

**Comment by Louis-Clelland** [comment]
Done

**Comment by john-rob-dev** [comment]
Ok then i will now merge this to the master branch thanks @Louis-Clelland

**Comment by john-rob-dev** [comment]
Done

**Pull request merged**
